//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    public sealed partial class CustomersListDetail
        : global::Microsoft.LightSwitch.Framework.Client.ScreenObject<global::LightSwitchApplication.CustomersListDetail, global::LightSwitchApplication.CustomersListDetail.DetailsClass>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private CustomersListDetail() : base("LightSwitchApplication.LightSwitchInvoice.DesktopClient:CustomersListDetail")
        {
            global::LightSwitchApplication.CustomersListDetail.DetailsClass.Initialize(this);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static CustomersListDetail CreateInstance()
        {
            return new global::LightSwitchApplication.CustomersListDetail(
            );
        }

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CustomersListDetail_InitializeDataWorkspace(global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CustomersListDetail_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CustomersListDetail_Activated();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CustomersListDetail_Saving(ref bool handled);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CustomersListDetail_Saved();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CustomersListDetail_Closing(ref bool cancel);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CustomersListDetail_SaveError(global::System.Exception exception, ref bool handled);
     
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)((global::Microsoft.LightSwitch.Details.Client.IScreenDetails)this.Details).DataWorkspace;
            }
        }
        
        #endregion
 
        partial void Customers_SelectionChanged();

        partial void Customers_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Customers_Loaded(bool succeeded);

        partial void Orders_SelectionChanged();

        partial void Orders_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Orders_Loaded(bool succeeded);

        partial void InvoiceDate_Changed();

        /// <summary>
        /// Gets the Customers visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.Customer> Customers
        {
            get
            {
                return global::LightSwitchApplication.CustomersListDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.CustomersListDetail.DetailsClass.PropertySetProperties.Customers);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Customers_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        /// <summary>
        /// Gets the Orders visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.Order> Orders
        {
            get
            {
                return global::LightSwitchApplication.CustomersListDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.CustomersListDetail.DetailsClass.PropertySetProperties.Orders);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Orders_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string InvoiceDate
        {
            get 
            {
                return global::LightSwitchApplication.CustomersListDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.CustomersListDetail.DetailsClass.PropertySetProperties.InvoiceDate);
            }
            set
            {
                global::LightSwitchApplication.CustomersListDetail.DetailsClass.SetValue(this, global::LightSwitchApplication.CustomersListDetail.DetailsClass.PropertySetProperties.InvoiceDate, value);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void InvoiceDate_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        /// <summary>
        /// Calls the Print screen method.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void Print()
        {
            this.Details.Methods.Print.CreateInvocation().Execute();
        }
        partial void Print_CanExecute(ref bool result);
        partial void Print_Execute();

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass
            : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.CustomersListDetail, global::LightSwitchApplication.CustomersListDetail.DetailsClass, global::LightSwitchApplication.CustomersListDetail.DetailsClass.PropertySet, global::LightSwitchApplication.CustomersListDetail.DetailsClass.CommandSet, global::LightSwitchApplication.CustomersListDetail.DetailsClass.MethodSet>
        {

            static DetailsClass()
            {
                var initializePropertyEntry = global::LightSwitchApplication.CustomersListDetail.DetailsClass.PropertySetProperties.Customers;
                var initializeCommandEntry = global::LightSwitchApplication.CustomersListDetail.DetailsClass.CommandSetProperties.Print;
                var initializeMethodEntry = global::LightSwitchApplication.CustomersListDetail.DetailsClass.MethodSetProperties.Print;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.CustomersListDetail, global::LightSwitchApplication.CustomersListDetail.DetailsClass>.Entry
                __CustomersListDetailEntry = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.CustomersListDetail, global::LightSwitchApplication.CustomersListDetail.DetailsClass>.Entry(
                    global::LightSwitchApplication.CustomersListDetail.DetailsClass.__CustomersListDetail_InvokeInitializeDataWorkspace,
                    global::LightSwitchApplication.CustomersListDetail.DetailsClass.__CustomersListDetail_InvokeSavingEvent,
                    global::LightSwitchApplication.CustomersListDetail.DetailsClass.__CustomersListDetail_InvokeSavedEvent,
                    global::LightSwitchApplication.CustomersListDetail.DetailsClass.__CustomersListDetail_InvokeClosingEvent,
                    global::LightSwitchApplication.CustomersListDetail.DetailsClass.__CustomersListDetail_InvokeCreated,
                    global::LightSwitchApplication.CustomersListDetail.DetailsClass.__CustomersListDetail_InvokeActivated,
                    global::LightSwitchApplication.CustomersListDetail.DetailsClass.__CustomersListDetail_InvokeSaveErrorEvent);
            private static void __CustomersListDetail_InvokeInitializeDataWorkspace(global::LightSwitchApplication.CustomersListDetail s, global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo)
            {
                s.CustomersListDetail_InitializeDataWorkspace(saveChangesTo);
            }
            private static bool __CustomersListDetail_InvokeSavingEvent(global::LightSwitchApplication.CustomersListDetail s)
            {
                bool handled = false;
                s.CustomersListDetail_Saving(ref handled);
                return handled;
            }
            private static void __CustomersListDetail_InvokeSavedEvent(global::LightSwitchApplication.CustomersListDetail s)
            {
                s.CustomersListDetail_Saved();
            }
            private static bool __CustomersListDetail_InvokeClosingEvent(global::LightSwitchApplication.CustomersListDetail s)
            {
                bool cancel = false;
                s.CustomersListDetail_Closing(ref cancel);
                return cancel;
            }
            private static void __CustomersListDetail_InvokeCreated(global::LightSwitchApplication.CustomersListDetail s)
            {
                s.CustomersListDetail_Created();
            }
            private static void __CustomersListDetail_InvokeActivated(global::LightSwitchApplication.CustomersListDetail s)
            {
                s.CustomersListDetail_Activated();
            }
            private static bool __CustomersListDetail_InvokeSaveErrorEvent(global::LightSwitchApplication.CustomersListDetail s, global::System.Exception ex)
            {
                bool handled = false;
                s.CustomersListDetail_SaveError(ex, ref handled);
                return handled;
            }

            public DetailsClass() : base()
            {
            }

            public new global::LightSwitchApplication.CustomersListDetail.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }

            public new global::LightSwitchApplication.CustomersListDetail.DetailsClass.CommandSet Commands
            {
                get
                {
                    return base.Commands;
                }
            }

            public new global::LightSwitchApplication.CustomersListDetail.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable CustomersQuery()
            {
                return this.Screen.DataWorkspace.ApplicationData.Customers;
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable OrdersQuery()
            {
                if (this.Screen.Customers.SelectedItem == null)
                {
                    return null;
                }

                global::Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Order> loader =
                    (global::Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Order>)((global::Microsoft.LightSwitch.Details.ILoadableProperty)this.Screen.Customers.SelectedItem.Details.Properties.Orders).Loader;
                if (loader == null)
                {
                    return null;
                }

                return loader;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.CustomersListDetail, global::LightSwitchApplication.CustomersListDetail.DetailsClass, global::LightSwitchApplication.Customer>.Data _Customers;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.CustomersListDetail, global::LightSwitchApplication.CustomersListDetail.DetailsClass, global::LightSwitchApplication.Order>.Data _Orders;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.CustomersListDetail, global::LightSwitchApplication.CustomersListDetail.DetailsClass, string>.Data _InvoiceDate;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.CustomersListDetail, global::LightSwitchApplication.CustomersListDetail.DetailsClass>.Data _PrintCommand;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.CustomersListDetail, global::LightSwitchApplication.CustomersListDetail.DetailsClass>.Data _PrintMethod;

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet<global::LightSwitchApplication.CustomersListDetail, global::LightSwitchApplication.CustomersListDetail.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.CustomersListDetail, global::LightSwitchApplication.CustomersListDetail.DetailsClass, global::LightSwitchApplication.Customer> Customers
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.CustomersListDetail, global::LightSwitchApplication.CustomersListDetail.DetailsClass, global::LightSwitchApplication.Customer>)base.GetItem(global::LightSwitchApplication.CustomersListDetail.DetailsClass.PropertySetProperties.Customers);
                    }
                }

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.CustomersListDetail, global::LightSwitchApplication.CustomersListDetail.DetailsClass, global::LightSwitchApplication.Order> Orders
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.CustomersListDetail, global::LightSwitchApplication.CustomersListDetail.DetailsClass, global::LightSwitchApplication.Order>)base.GetItem(global::LightSwitchApplication.CustomersListDetail.DetailsClass.PropertySetProperties.Orders);
                    }
                }

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.CustomersListDetail, global::LightSwitchApplication.CustomersListDetail.DetailsClass, string> InvoiceDate
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.CustomersListDetail, global::LightSwitchApplication.CustomersListDetail.DetailsClass, string>)base.GetItem(global::LightSwitchApplication.CustomersListDetail.DetailsClass.PropertySetProperties.InvoiceDate);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class CommandSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet<global::LightSwitchApplication.CustomersListDetail, global::LightSwitchApplication.CustomersListDetail.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.CustomersListDetail, global::LightSwitchApplication.CustomersListDetail.DetailsClass> Print
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.CustomersListDetail, global::LightSwitchApplication.CustomersListDetail.DetailsClass>)base.GetItem(global::LightSwitchApplication.CustomersListDetail.DetailsClass.CommandSetProperties.Print);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet<global::LightSwitchApplication.CustomersListDetail, global::LightSwitchApplication.CustomersListDetail.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.CustomersListDetail, global::LightSwitchApplication.CustomersListDetail.DetailsClass> Print
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.CustomersListDetail, global::LightSwitchApplication.CustomersListDetail.DetailsClass>)base.GetItem(global::LightSwitchApplication.CustomersListDetail.DetailsClass.MethodSetProperties.Print);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class PropertySetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.CustomersListDetail, global::LightSwitchApplication.CustomersListDetail.DetailsClass, global::LightSwitchApplication.Customer>.Entry
                    Customers = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.CustomersListDetail, global::LightSwitchApplication.CustomersListDetail.DetailsClass, global::LightSwitchApplication.Customer>.Entry(
                        "Customers",
                        global::LightSwitchApplication.CustomersListDetail.DetailsClass.PropertySetProperties._Customers_Stub,
                        global::LightSwitchApplication.CustomersListDetail.DetailsClass.PropertySetProperties._Customers_Validate,
                        global::LightSwitchApplication.CustomersListDetail.DetailsClass.PropertySetProperties._Customers_CreateQuery,
                        global::LightSwitchApplication.CustomersListDetail.DetailsClass.PropertySetProperties._Customers_SelectionChanged,
                        global::LightSwitchApplication.CustomersListDetail.DetailsClass.PropertySetProperties._Customers_OnCollectionChanged,
                        global::LightSwitchApplication.CustomersListDetail.DetailsClass.PropertySetProperties._Customers_OnLoaded);
                private static void _Customers_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CustomersListDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.CustomersListDetail, global::LightSwitchApplication.CustomersListDetail.DetailsClass, global::LightSwitchApplication.Customer>.Data> c, global::LightSwitchApplication.CustomersListDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._Customers, sf);
                }
                private static void _Customers_Validate(global::LightSwitchApplication.CustomersListDetail s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.Customers_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _Customers_CreateQuery(global::LightSwitchApplication.CustomersListDetail.DetailsClass d, object[] args)
                {
                    return d.CustomersQuery();
                }
                private static void _Customers_SelectionChanged(global::LightSwitchApplication.CustomersListDetail s)
                {
                    s.Customers_SelectionChanged();
                }
                private static void _Customers_OnCollectionChanged(global::LightSwitchApplication.CustomersListDetail s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.Customers_Changed(e);
                }
                private static void _Customers_OnLoaded(global::LightSwitchApplication.CustomersListDetail s, bool succeeded)
                {
                    s.Customers_Loaded(succeeded);
                }

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.CustomersListDetail, global::LightSwitchApplication.CustomersListDetail.DetailsClass, global::LightSwitchApplication.Order>.Entry
                    Orders = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.CustomersListDetail, global::LightSwitchApplication.CustomersListDetail.DetailsClass, global::LightSwitchApplication.Order>.Entry(
                        "Orders",
                        global::LightSwitchApplication.CustomersListDetail.DetailsClass.PropertySetProperties._Orders_Stub,
                        global::LightSwitchApplication.CustomersListDetail.DetailsClass.PropertySetProperties._Orders_Validate,
                        global::LightSwitchApplication.CustomersListDetail.DetailsClass.PropertySetProperties._Orders_CreateQuery,
                        global::LightSwitchApplication.CustomersListDetail.DetailsClass.PropertySetProperties._Orders_SelectionChanged,
                        global::LightSwitchApplication.CustomersListDetail.DetailsClass.PropertySetProperties._Orders_OnCollectionChanged,
                        global::LightSwitchApplication.CustomersListDetail.DetailsClass.PropertySetProperties._Orders_OnLoaded);
                private static void _Orders_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CustomersListDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.CustomersListDetail, global::LightSwitchApplication.CustomersListDetail.DetailsClass, global::LightSwitchApplication.Order>.Data> c, global::LightSwitchApplication.CustomersListDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._Orders, sf);
                }
                private static void _Orders_Validate(global::LightSwitchApplication.CustomersListDetail s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.Orders_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _Orders_CreateQuery(global::LightSwitchApplication.CustomersListDetail.DetailsClass d, object[] args)
                {
                    return d.OrdersQuery();
                }
                private static void _Orders_SelectionChanged(global::LightSwitchApplication.CustomersListDetail s)
                {
                    s.Orders_SelectionChanged();
                }
                private static void _Orders_OnCollectionChanged(global::LightSwitchApplication.CustomersListDetail s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.Orders_Changed(e);
                }
                private static void _Orders_OnLoaded(global::LightSwitchApplication.CustomersListDetail s, bool succeeded)
                {
                    s.Orders_Loaded(succeeded);
                }

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.CustomersListDetail, global::LightSwitchApplication.CustomersListDetail.DetailsClass, string>.Entry
                    InvoiceDate = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.CustomersListDetail, global::LightSwitchApplication.CustomersListDetail.DetailsClass, string>.Entry(
                        "InvoiceDate",
                        false,
                        global::LightSwitchApplication.CustomersListDetail.DetailsClass.PropertySetProperties._InvoiceDate_Stub,
                        global::LightSwitchApplication.CustomersListDetail.DetailsClass.PropertySetProperties._InvoiceDate_Validate,
                        global::LightSwitchApplication.CustomersListDetail.DetailsClass.PropertySetProperties._InvoiceDate_OnValueChanged);
                private static void _InvoiceDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CustomersListDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.CustomersListDetail, global::LightSwitchApplication.CustomersListDetail.DetailsClass, string>.Data> c, global::LightSwitchApplication.CustomersListDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._InvoiceDate, sf);
                }
                private static void _InvoiceDate_Validate(global::LightSwitchApplication.CustomersListDetail s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.InvoiceDate_Validate(r);
                }
                private static void _InvoiceDate_OnValueChanged(global::LightSwitchApplication.CustomersListDetail s)
                {
                    s.InvoiceDate_Changed();
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class CommandSetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.CustomersListDetail, global::LightSwitchApplication.CustomersListDetail.DetailsClass>.Entry
                    Print = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.CustomersListDetail, global::LightSwitchApplication.CustomersListDetail.DetailsClass>.Entry(
                        "Print",
                        global::LightSwitchApplication.CustomersListDetail.DetailsClass.CommandSetProperties._Print_Stub,
                        global::LightSwitchApplication.CustomersListDetail.DetailsClass.CommandSetProperties._Print_CreateExecutableObject);
                private static void _Print_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CustomersListDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.CustomersListDetail, global::LightSwitchApplication.CustomersListDetail.DetailsClass>.Data> c, global::LightSwitchApplication.CustomersListDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._PrintCommand, sf);
                }
                private static global::Microsoft.LightSwitch.IExecutable _Print_CreateExecutableObject(global::LightSwitchApplication.CustomersListDetail.DetailsClass d)
                {
                    return ((global::LightSwitchApplication.CustomersListDetail.DetailsClass)d).Methods.Print.CreateInvocation();
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class MethodSetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.CustomersListDetail, global::LightSwitchApplication.CustomersListDetail.DetailsClass>.Entry
                    Print = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.CustomersListDetail, global::LightSwitchApplication.CustomersListDetail.DetailsClass>.Entry(
                        "Print",
                        global::LightSwitchApplication.CustomersListDetail.DetailsClass.MethodSetProperties._Print_Stub,
                        global::LightSwitchApplication.CustomersListDetail.DetailsClass.MethodSetProperties._Print_CanInvoke,
                        global::LightSwitchApplication.CustomersListDetail.DetailsClass.MethodSetProperties._Print_InvokeMethod);
                private static void _Print_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CustomersListDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.CustomersListDetail, global::LightSwitchApplication.CustomersListDetail.DetailsClass>.Data> c, global::LightSwitchApplication.CustomersListDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._PrintMethod, sf);
                }
                private static global::System.Exception _Print_CanInvoke(global::LightSwitchApplication.CustomersListDetail.DetailsClass d, global::System.Collections.ObjectModel.ReadOnlyCollection<object> args, global::System.Exception ex)
                {
                    bool result = true;
                    d.Screen.Print_CanExecute(ref result);
                    return result ? null : ex;
                }
                private static void _Print_InvokeMethod(global::LightSwitchApplication.CustomersListDetail.DetailsClass d, global::System.Collections.ObjectModel.ReadOnlyCollection<object> args)
                {
                    d.Screen.Print_Execute();
                }

            }
        }
    }
}
